apiVersion: v1
kind: Namespace
metadata:
  name: rabbit

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: rabbit
  name: rabbit
  namespace: rabbit
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: rabbit
  template:
    metadata:
      labels:
        k8s-app: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
              protocol: TCP
 
---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: rabbit
  name: rabbit
  namespace: rabbit
spec:
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    k8s-app: rabbit

---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: rabbit
  name: rabbit-management
  namespace: rabbit
spec:
  ports:
    - port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    k8s-app: rabbit

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rabbit-management
  namespace: rabbit
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pipr.io`) && PathPrefix(`/rabbit`)
      kind: Rule
      middlewares:
      - name: rabbit-stripprefix
      services:
        - name: rabbit-management
          port: 15672

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rabbit-stripprefix
  namespace: rabbit
spec:
  stripPrefix:
    prefixes:
      - /rabbit
---

apiVersion: v1
kind: Service
metadata:
  name: rabbit-node
  namespace: rabbit
spec:
  type: NodePort
  selector:
    k8s-app: rabbit
  ports:
    - port: 5672
      targetPort: 5672
      nodePort: 31933
