name: 'Initialize S3 bucket for Terraform'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-central-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform -chdir=init init
      env:
        TF_VAR_WORKBENCH: ${{ secrets.WORKBENCH_PK }}

    - name: Terraform Plan
      run: terraform -chdir=init plan -lock=false
      env:
        TF_VAR_WORKBENCH: ${{ secrets.WORKBENCH_PK }}

    - name: Terraform Apply
      run: terraform -chdir=init apply -auto-approve -lock=false
      env:
        TF_VAR_WORKBENCH: ${{ secrets.WORKBENCH_PK }}